insightink/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('accounts/signup', views.signup, name='signup'),
  path('', views.home, name='home'),
  path('journals/', views.journals_index, name='journals_index'),
  path('journals/create/', views.journals_create, name='journals_create'),
  path('journals/<int:pk>/update/', views.JournalUpdate.as_view(), name='journals_update'),
  path('journals/<int:pk>/delete/', views.JournalDelete.as_view(), name='journals_delete'),
  path('journals/<int:journal_id>/', views.journals_detail, name='detail'),
  path('journals/<int:journal_id>/add_entry/', views.add_entry, name='add_entry'),
  path('entries/<int:pk>/update/', views.EntryUpdate.as_view(), name='entry_update'),
  path('entries/<int:pk>/delete/', views.EntryDelete.as_view(), name='entry_delete'),
  path('entries/<int:entry_id>/', views.entry_detail, name='entry_detail'),
  path('travels/<int:pk>/update/', views.TravelUpdate.as_view(), name='travel_update'),
  path('travels/<int:pk>/delete/', views.TravelDelete.as_view(), name='travel_delete'),
  path('travel/<int:travel_id>/', views.travel_detail, name='travel_detail'),
  path('wellness/<int:pk>/update/', views.WellnessUpdate.as_view(), name='wellness_update'),
  path('wellness/<int:pk>/delete/', views.WellnessDelete.as_view(), name='wellness_delete'),
  path('wellness/<int:w_id>/', views.wellness_detail, name='wellness_detail'),
  path('travels/<int:travel_id>/add_photo/', views.add_photo, name='add_photo'),
  path('photo/<int:pk>/delete/', views.PhotoDelete.as_view(), name='photo_delete'),
  path('travels/', views.travels_index, name='travels_index'),
  path('wellness/', views.wellness_index, name='wellness_index'),
  path('personal/', views.personal_index, name='personal_index'),
  
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

TEMPLATES = (
  ('P', 'Personal'),
  ('T', 'Travel'),
  ('H', 'Wellness'),
  ('W', 'Work'),
)

WEATHER_TYPES = (
  ('S', 'Sunny ☀️'),
  ('C', 'Cloudy ☁️'),
  ('R', 'Rainy 🌧️'),
  ('T', 'Thunderstorm ⛈️'),
  ('N', 'Snowy ❄️'),
  ('W', 'Windy 🌬️'),
  ('F', 'Foggy 🌫️'),
) 

MOODS = (
  ('H', 'Happy 😊'),
  ('S', 'Sad 😢'),
  ('C', 'Content 😌'),
  ('A', 'Angry 😡'),
  ('T', 'Tired 🥱'),
  ('X', 'Anxious 😰'),
  ('K', 'Sick 🤒'),
)

# Create your models here.
class Journal(models.Model):
  name = models.CharField(max_length=50)
  template = models.CharField(
	max_length=1,
	choices=TEMPLATES,
	default=TEMPLATES[0][0]
  )
  created_at = models.DateField(default=timezone.now)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  class Meta:
    ordering = ['-updated_at']

  def __str__(self):
    return f"journal.id: {self.id}, user {self.user.id}: {self.user},  name: '{self.name}', template: {self.get_template_display()}"
  
  def get_absolute_url(self):
    return reverse('journals_index')
  
  def has_entries(self):
    return self.entry_set.exists()
  
  def is_empty(self):
    empty = not self.entry_set.exists() and not self.travel_set.exists() and not self.wellness_set.exists()
    return empty
  
  def is_travel(self):
    return self.template == 'T'
  
  def is_wellness(self):
    return self.template == 'H'
  
  def count(self):
    if self.is_travel():
      return self.travel_set.count()
    elif self.is_wellness():
      return self.wellness_set.count()
    else:
      return self.entry_set.count() 



class Entry(models.Model):
  title = models.CharField(max_length=50)
  date = models.DateField()
  body = models.TextField(max_length=1000)
  notes = models.TextField(max_length=300)
  mood = models.CharField(
	max_length=1,
	choices=MOODS,
	default=MOODS[0][0]
  )

  created_at = models.DateField(default=timezone.now)
  updated_at = models.DateTimeField(auto_now=True)
  journal = models.ForeignKey(Journal, on_delete=models.CASCADE)

  class Meta:
    ordering = ['-updated_at']

  def __str__(self):
    return f"journal_id: {self.journal.id}, user {self.journal.user.id}: {self.journal.user} , '{self.title}'"
  
  def get_absolute_url(self):
    return reverse('detail', kwargs={'journal_id': self.journal_id})
  
  def mood_display(self):
    return self.get_mood_display()
  


class Travel(models.Model):
  title = models.CharField(max_length=50)
  date = models.DateField()
  body = models.TextField(max_length=1000)
  notes = models.TextField(max_length=300)
  mood = models.CharField(
	max_length=1,
	choices=MOODS,
	default=MOODS[0][0]
  )
  location = models.CharField(max_length=50)
  food = models.TextField(max_length=150)
  weather = models.CharField(
	max_length=1,
	choices=WEATHER_TYPES,
	default=WEATHER_TYPES[0][0]
  )
  created_at = models.DateField(default=timezone.now)
  updated_at = models.DateTimeField(auto_now=True)
  journal = models.ForeignKey(Journal, on_delete=models.CASCADE)

  class Meta:
    ordering = ['-updated_at']

  def __str__(self):
    return f"journal_id: {self.journal.id}, user {self.journal.user.id}: {self.journal.user} , template: {self.journal.template}, '{self.title}'"
  
  def weather_display(self):
    return self.get_weather_display()
  
  def mood_display(self):
    return self.get_mood_display()
  
  def get_absolute_url(self):
    return reverse('detail', kwargs={'journal_id': self.journal_id})
  


class Wellness(models.Model):
  title = models.CharField(max_length=50)
  date = models.DateField()
  body = models.TextField(max_length=1000)
  notes = models.TextField(max_length=300)
  affirmation = models.TextField(max_length=200)
  food = models.TextField(max_length=150)
  sleep = models.IntegerField()
  mood = models.CharField(
	max_length=1,
	choices=MOODS,
	default=MOODS[0][0]
  )

  created_at = models.DateField(default=timezone.now)
  updated_at = models.DateTimeField(auto_now=True)
  journal = models.ForeignKey(Journal, on_delete=models.CASCADE)

  def mood_display(self):
    return self.get_mood_display()

  def get_absolute_url(self):
    return reverse('detail', kwargs={'journal_id': self.journal_id})
  
  def __str__(self):
    return f"journal_id: {self.journal.id}, user {self.journal.user.id}: {self.journal.user} , template: {self.journal.template}, '{self.title}'"
  
class Photo(models.Model):
    url = models.CharField(max_length=200)
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for travel_id: {self.travel_id} @{self.url}"  
    
    def get_absolute_url(self):
      return reverse('travel_detail', kwargs={'travel_id': self.travel_id})

main_app/forms.py
from django.forms import ModelForm
from .models import Journal, Entry, Travel, Wellness


class JournalForm(ModelForm):
    class Meta:
        model = Journal
        fields = ['name', 'template']

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'body', 'date', 'mood', 'notes']

class TravelForm(ModelForm):
    class Meta:
        model = Travel
        fields = ['title', 'body', 'date', 'mood', 'location', 'food', 'weather', 'notes']

class WellnessForm(ModelForm):
    class Meta:
        model = Wellness
        fields = ['title', 'body', 'date', 'mood', 'affirmation', 'sleep', 'food', 'notes']        

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Journal, Entry, Travel, Wellness, Photo
from .forms import JournalForm, EntryForm, TravelForm, WellnessForm

# Create your views here.
# @login_required -> auth decorator for view functions
# LoginRequiredMixin -> auth mixin for CBV

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


def home(request):
  return render(request, 'home.html')


def journals_index(request):
  journals = Journal.objects.filter(user=request.user)
  user = request.user
  return render(request, 'journals/index.html', { 'journals': journals, 'user': user })


@login_required
def journals_create(request):
  error_message = ''
  journal_form = JournalForm(request.POST)
  user = request.user.id
  if journal_form.is_valid():
    new_journal = journal_form.save(commit=False)
    new_journal.user_id = user
    new_journal.save()
    return redirect(journals_index)
  else:
    error_message = "Invalid journal creation - try again"
  return render(request, 'journals/journal_form.html', { 
    'journal_form': journal_form,
    'error_message': error_message
  })


class JournalUpdate(LoginRequiredMixin, UpdateView):
  model = Journal
  fields = ['name']


class JournalDelete(LoginRequiredMixin, DeleteView):
  model = Journal
  success_url = '/journals'


@login_required
def journals_detail(request, journal_id):
  journal = Journal.objects.get(id=journal_id)

  if journal.template == 'H':
    print('wellness')
    wellness = journal.wellness_set.all()
    return render(request, 'journals/detail.html', {
    'journal': journal,
    'wellness': wellness
  })
  elif journal.is_travel():
    print('travel')
    travels = journal.travel_set.all()
    return render(request, 'journals/detail.html', {
    'journal': journal,
    'travels': travels
  })
  if journal.is_empty():
    return render(request, 'journals/detail.html', {
    'journal': journal,
  })

  elif journal.has_entries():
    print('entries')
    entries = journal.entry_set.all()
    return render(request, 'journals/detail.html', {
    'journal': journal,
    'entries': entries,
  })


@login_required
def add_entry(request, journal_id):
  error_message = ''
  journal = Journal.objects.get(id=journal_id)

  if journal.is_travel():
    entry_form = TravelForm(request.POST)
  elif journal.is_wellness():
    entry_form = WellnessForm(request.POST)  
  else:
    entry_form = EntryForm(request.POST)

  journal = journal.id
  if entry_form.is_valid():
    new_entry = entry_form.save(commit=False)
    new_entry.journal_id = journal_id
    new_entry.save()
    return redirect('detail', journal_id=journal_id)
  else:
    error_message = "Invalid entry creation - try again"
  return render(request, 'journals/entry_form.html', { 
    'journal' : journal,
    'entry_form': entry_form,
    'error_message': error_message
  })


class EntryUpdate(LoginRequiredMixin, UpdateView):
  model = Entry
  fields = ['title', 'date', 'body', 'mood', 'notes']


class EntryDelete(LoginRequiredMixin, DeleteView):
  model = Entry
  def get_success_url(self):
    return self.object.get_absolute_url()
  


def entry_detail(request, entry_id):
  entry = Entry.objects.get(id=entry_id)
  return render(request, 'entry/detail.html', {
    'entry': entry
  })


class TravelUpdate(LoginRequiredMixin, UpdateView):
  model = Travel
  fields = ['title', 'date', 'body', 'mood', 'location', 'food', 'weather', 'notes']


class TravelDelete(LoginRequiredMixin, DeleteView):
  model = Travel
  def get_success_url(self):
    return self.object.get_absolute_url()

def travel_detail(request, travel_id):
  travel = Travel.objects.get(id=travel_id)
  return render(request, 'entry/travel_detail.html', {
    'travel': travel
  })
  
class WellnessUpdate(LoginRequiredMixin, UpdateView):
  model = Wellness
  fields = ['title', 'body', 'date', 'mood', 'affirmation', 'sleep', 'food', 'notes']   


class WellnessDelete(LoginRequiredMixin, DeleteView):
  model = Wellness
  def get_success_url(self):
    return self.object.get_absolute_url()
  
  
def wellness_detail(request, w_id):
  wellness = Wellness.objects.get(id=w_id)
  return render(request, 'entry/wellness_detail.html', {
    'wellness': wellness
  })

def add_photo(request, travel_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, travel_id=travel_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('travel_detail', travel_id=travel_id)


def travels_index(request):
  journals = Journal.objects.filter(user=request.user, template = 'T')
  user = request.user
  return render(request, 'journals/index.html', { 'journals': journals, 'user': user })


def wellness_index(request):
  journals = Journal.objects.filter(user=request.user, template = 'H')
  user = request.user
  return render(request, 'journals/index.html', { 'journals': journals, 'user': user })


def personal_index(request):
  journals = Journal.objects.filter(user=request.user, template = 'P')
  user = request.user
  return render(request, 'journals/index.html', { 'journals': journals, 'user': user })



class PhotoDelete(LoginRequiredMixin, DeleteView):
  model = Photo
  def get_success_url(self):
    return self.object.get_absolute_url()

main_app/templates/journals/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="title-nav">
  <h1>Journal: <span class="bluey-text">{{ journal.name }}</span></h1>
  <div class="breadcrumb-container">
    <a href="{% url 'journals_index' %}" class="breadcrumb">My Journals</a>
    <span class="breadcrumb">{{journal.get_template_display}}</span>
  </div>
  <div>
    <a href="{% url 'add_entry' journal.id %}" class="btn-floating btn-large waves-effect waves-light red"><i
        class="material-icons">add</i></a>
  </div>
</div>


{% if journal.is_empty %}
<div class="card-panel red-text center-align">{{journal.name}} has no entries</div>

{% elif journal.template == 'T' %}
<div class="row entries-container">
  {% for travel in travels %}
  <div class="col s4">
    <div class="card">
      <div class="card-content">
        <div class="display-field body-desc" id="entry-card">
          <a href="{% url  'travel_detail' travel.id %}">
            <h3>{{travel.title }}</h3>
          </a>
        </div>
        <div class="display-field affirmations" id="index">
          <p>Created at: {{travel.updated_at}}</p>
          <p> Date: {{travel.date}} </p>
          <p> Content: {{travel.body}} </p>
          <p> Mood: {{travel.mood_display}}</p>
          <p> Location: {{travel.location}}</p>
          <p> Food: {{travel.food}}</p>
          <p> Weather: {{travel.weather_display}}</p>
          <p> Notes: {{travel.notes}}</p>

        </div>
        <div class="card-action">
          <a href="{% url 'travel_update' travel.id %}">Edit</a>
          <a href="{% url 'travel_delete' travel.id %}">Delete</a>
        </div>
      </div>
    </div>

  </div>
  {% endfor %}
</div>


{% elif journal.template == 'H' %}
<div class="row entries-container">
  {% for w in wellness %}
  <div class="col s4">
    <div class="card">
      <div class="card-content">
        <div class="display-field body-desc" id="entry-card">
          <a href="{% url  'wellness_detail' w.id %}">
            <h3>{{w.title }}</h3>
          </a>
        </div>
        <div class="display-field affirmations" id="index">
          <p>Updated at: {{w.updated_at}}</p>
          <p> Date: {{w.date}} </p>
          <p> Content: {{w.body}} </p>
          <p> Mood: {{w.mood_display}}</p>
          <p> Affirmations: {{w.affirmation}}</p>
          <p> Food: {{w.food}}</p>
          <p> Sleep: {{w.sleep}} hrs</p>
          <p> Notes: {{w.notes}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'wellness_update' w.id %}">Edit</a>
          <a href="{% url 'wellness_delete' w.id %}">Delete</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% elif journal.has_entries %}
<div class="row entries-container">
  {% for entry in entries %}
  <div class="col s4">
    <div class="card">
      <div class="card-content detail-sizing">
        <div class="display-field body-desc" id="entry-card">
          <a href="{% url  'entry_detail' entry.id %}">
            <h3>{{entry.title}}</h3>
          </a>

        </div>
        <div class="display-field affirmations" id="index">
          <p> Date: {{entry.date}} </p>
          <p> Content: {{entry.body}} </p>
          <p> Mood: {{entry.mood_display}}</p>
          <p>Notes: {{entry.notes}}</p>

        </div>
        <div class="card-action">
          <a href="{% url 'entry_update' entry.id %}">Edit</a>
          <a href="{% url 'entry_delete' entry.id %}">Delete</a>
        </div>
      </div>
    </div>

  </div>
  {% endfor %}
</div>

{% endif %}

<script>
  const paragraphs = document.querySelectorAll('#index p');
  paragraphs.forEach(paragraph => {
    const text = paragraph.innerHTML;
    const parts = text.split(':');
    if (parts.length > 1) {
      parts[0] = `<span class="bold-label">${parts[0]}:</span>`;
      paragraph.innerHTML = parts.join('');
    }
  });

  const upper = document.querySelectorAll('h3');
  upper.forEach(header => {
    const text = header.innerHTML;
    const upperCaseText = text.charAt(0).toUpperCase() + text.slice(1);
    header.innerHTML = upperCaseText;
  })
</script>



{% endblock %}

main_app/templates/journals/entry_form.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center">Create an Entry</h1>

<div class="entry-form-container">
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ entry_form.as_table }}
    </table>
    <div class="entry-form-submit">
      <a href="{% url 'detail' journal %}">Cancel</a>
      <input type="submit" value="Submit!" class="btn">
    </div>
  </form>
</div>



<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_weather');
  M.FormSelect.init(selectEl);

  const moodEl = document.getElementById('id_mood');
  M.FormSelect.init(moodEl);

</script>

{% endblock %}

main_app/templates/journals/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1 class="center">{{user}}'s Journals</h1>
{% if user.journal_set.count == 0 %}
<div class="card-panel red-text center-align">{{user}} has no Journals</div>
{% endif %}
<div class="row">
    {% for journal in journals %}
    <div class="col s4">
        <div class="card journal-card">
            <div class="card-image waves-effect waves-block waves-light">
                {% if journal.template == 'T' %}
                <img class="activator journal-image" src="{% static 'images/travel.jpg' %}">
                {% elif journal.template == 'P' %}
                <img class="activator journal-image" src="{% static 'images/personal.jpg' %}">
                {% elif journal.template == 'H' %}
                <img class="activator journal-image" src="{% static 'images/wellness.jpg' %}">
                {% elif journal.template == 'W' %}
                <img class="activator journal-image " src="{% static 'images/work.jpg' %}">
                {% endif %}
            </div>
            <div class="journal-card-content">
                <span class="card-title activator grey-text text-darken-4">{{ journal.name }}<i
                        class="material-icons right">more_vert</i></span>
                <a href="{% url 'detail' journal.id %}">
                    <p>Journal Type: {{ journal.get_template_display }}</p>
                </a>
            </div>
            <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">{{ journal.name }}<i
                        class="material-icons right">close</i></span>
                <p>Journal Type: {{ journal.get_template_display }}</p>
                <p>Entries: {{ journal.count }}</p>
                <div class="card-action">
                    <a href="{% url 'journals_update' journal.id %}">Edit</a>
                    <a href="{% url 'journals_delete' journal.id %}">Delete</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

main_app/templates/journals/journal_form.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center">Create a Journal</h1>

<div class="entry-form-container">
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ journal_form.as_table }}
    </table>
    <div class="entry-form-submit">
      <a href="{% url 'journals_index' %}">Cancel</a>
      <input type="submit" value="Submit!" class="btn">
    </div>
  </form>
</div>

<script>
  const selectEl = document.getElementById('id_template');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}